#!/usr/bin/with-contenv sh
# shellcheck shell=sh

if [[ "$RESTART_SECONDS" != "" ]]; then
  echo Restart enabled at $RESTART_SECONDS; date; sleep $RESTART_SECONDS; echo Restarting; kill -9 1; exit 1
fi